### ISSUE TITLE
conflict with song trigger

### ISSUE THREAD

**Issue by xHugoLA** [Alphalaneous/Improved-Song-Browser#1]
there is a conflict with the editor's song menu and the song trigger, even when choosing the default song, says that it is in use, or if you choose a different song, it changes the default song along with it.

video to see better: (link because the video is over 10mb)
https://cdn.discordapp.com/attachments/669765623726997514/1316471747939274802/streamable-bktjv6.mp4?ex=675b2b5b&is=6759d9db&hm=3d73e8646a5277f3e9e56b22f7dddfd78b6efbbb9f2cb2fe8c832ba8de103592&

**Comment by Alphalaneous** [comment]
Fixed, whoopsies
